### ISSUE TITLE
As a user I would like to add group tags to identify myself as part of a group

### ISSUE THREAD

**Issue by rug1** [katpas/cef2dwhe#39]
- from dropdown
- or create your own
- prevent script injections

**Comment by katpas** [comment]
- Add group tag to database

**Comment by katpas** [comment]
Styling needs adding, no drop down. Text input box.

**Comment by katpas** [comment]
Or could just make this a field (no cos styling) will save time and have the same effect e.g. As one of your profile lines it says groups #fac #CamdenCluster. Means you could do ctrl f to search through too on location list page @rachblondon

**Comment by katpas** [comment]
add placeholder in html to show example groups
