### ISSUE TITLE
Technical: Navigation (burger) menu. 

### ISSUE THREAD

**Issue by katpas** [katpas/cef2dwhe#45]
Includes: 
- location list page
- logout

**Comment by RachBLondon** [comment]
I think the default bootstrap nav-bar collapses to a burger menu on mobile sized screen http://getbootstrap.com/components/#navbar-default

**Comment by RachBLondon** [comment]
done for myProfile page, PR made. Need to add content to bar and to other html pages.

**Comment by katpas** [comment]
Finished and linked by @RachBLondon
