### ISSUE TITLE
As a user I want to send a match request to people I want to meet and pass on those I don't

### ISSUE THREAD

**Issue by katpas** [katpas/cef2dwhe#9]
- Write matching structure based on database research.

**Comment by katpas** [comment]
- Added cookie placeholder in matchPage.html for current UserID (need to hook this to api). 
- placeholder for matchee ID (get from api/db or front-end) 
- function connected to search database and return to handler status of match. 

ToDo: 
- if null add hmset function to add match request to matchee book.
- check user 2 to see if match request in their match book. 
- if match request already or matched/ front end pop up box.

**Comment by rug1** [comment]
Add error handling

**Comment by katpas** [comment]
Completed by @rug1 & katpas - error handling and testing moved to separate issue
